/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import DAO.DocGiaDAO;
import DTO.DocGiaDTO;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author dinhp
 */
public class DocgiaGUI extends javax.swing.JPanel {
    private DocGiaDAO docGiaDAO;
    private ArrayList<DocGiaDTO> listDocGia;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    /**
     * Creates new form Intro
     */
    public DocgiaGUI() {
        initComponents();
        setupComponents();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnlMain = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();
        pnlForm = new javax.swing.JPanel();
        lblTenDocGia = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        txtTenDocGia = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        cboGioiTinh = new javax.swing.JComboBox<>();
        lblMaThe = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        lblNgayCap = new javax.swing.JLabel();
        lblNgayHetHan = new javax.swing.JLabel();
        dateNgayHetHan = new com.toedter.calendar.JDateChooser();
        dateNgayCap = new com.toedter.calendar.JDateChooser();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKhoiPhuc = new javax.swing.JButton();
        pnlSearch = new javax.swing.JPanel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        scrTable = new javax.swing.JScrollPane();
        tblDocGia = new javax.swing.JTable();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1210, 640));

        pnlMain.setPreferredSize(new java.awt.Dimension(1210, 640));

        pnlContent.setPreferredSize(new java.awt.Dimension(1210, 640));

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        lblTenDocGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTenDocGia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenDocGia.setText("Tên độc giả:");

        lblGioiTinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGioiTinh.setText("Giới tính:");

        lblNgaySinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgaySinh.setText("Ngày sinh:");

        lblSoDienThoai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSoDienThoai.setText("Số điện thoại:");

        txtTenDocGia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenDocGia.setText("");

        txtSoDienThoai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoDienThoai.setText("");

        cboGioiTinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        lblMaThe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaThe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaThe.setText("Mã thẻ:");

        txtMaThe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaThe.setText("");

        lblNgayCap.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNgayCap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgayCap.setText("Ngày cấp:");

        lblNgayHetHan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNgayHetHan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgayHetHan.setText("Ngày hết hạn:");

        lblDiaChi.setFont(new java.awt.Font("Arial", 1, 14));
        lblDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiaChi.setText("Địa chỉ:");

        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14));
        txtDiaChi.setText("");

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenDocGia))
                .addGap(28, 28, 28)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                                .addComponent(lblMaThe)
                                .addGap(28, 28, 28)
                                .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNgayHetHan))
                                .addGap(28, 28, 28)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateNgayCap, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(dateNgayHetHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(100, 100, 100))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaThe))
                                .addGap(25, 25, 25)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNgayCap)
                                            .addComponent(dateNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNgayHetHan)
                                            .addComponent(dateNgayHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblGioiTinh)
                                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSoDienThoai)
                                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTenDocGia)))
                        .addGap(28, 28, 28)
                        .addComponent(lblNgaySinh))
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        btnThem.setContentAreaFilled(false);

        btnCapNhat.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        btnCapNhat.setContentAreaFilled(false);

        btnXoa.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        btnXoa.setContentAreaFilled(false);

        btnKhoiPhuc.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        btnKhoiPhuc.setContentAreaFilled(false);

        pnlSearch.setBackground(new java.awt.Color(0, 122, 77));

        lblTimKiem.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        lblTimKiem.setText("Tìm kiếm:");

        txtTimKiem.setBackground(new java.awt.Color(238, 242, 240));
        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtTimKiem.setText("");

        btnTimKiem.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(0, 122, 77));
        btnTimKiem.setText("Tìm kiếm");

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimKiem)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(10, 10, 10))
        );

        scrTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblDocGia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ĐG", "Tên độc giả", "Giới tính", "Số điện thoại", "Tuổi", "Địa chỉ", "Mã thẻ", "Ngày cấp", "Ngày hết hạn", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, 
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class, java.lang.String.class, 
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDocGia.setGridColor(new java.awt.Color(0, 0, 0));
        tblDocGia.setRowHeight(35);
        tblDocGia.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblDocGia.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblDocGia.setShowVerticalLines(true);
        scrTable.setViewportView(tblDocGia);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrTable)
                    .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrTable, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setupComponents() {
        // Khởi tạo DAO
        docGiaDAO = new DocGiaDAO();
        
        // Xóa text mặc định
        txtTenDocGia.setText("");
        txtSoDienThoai.setText("");
        txtMaThe.setText("");
        txtTimKiem.setText("");
        
        // Thêm sự kiện cho các nút
        btnThem.addActionListener(e -> themDocGia());
        btnCapNhat.addActionListener(e -> capNhatDocGia());
        btnXoa.addActionListener(e -> xoaDocGia());
        btnKhoiPhuc.addActionListener(e -> khoiPhucDocGia());
        btnTimKiem.addActionListener(e -> timKiemDocGia());
        
        // Thêm sự kiện cho bảng
        tblDocGia.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                hienThiChiTietDocGia();
            }
        });
    }
    
    private void loadDataToTable() {
        listDocGia = docGiaDAO.getList();
        DefaultTableModel model = (DefaultTableModel) tblDocGia.getModel();
        model.setRowCount(0);
        
        for (DocGiaDTO dg : listDocGia) {
            model.addRow(new Object[]{
                dg.getMaDG(),
                dg.getTenDG(),
                dg.getGioiTinh(),
                dg.getSoDienThoai(),
                tinhTuoi(dg.getNgaySinh()),
                dg.getDiaChi(),
                dg.getMaThe(),
                dg.getNgayCap() != null ? sdf.format(dg.getNgayCap()) : "",
                dg.getNgayHetHan() != null ? sdf.format(dg.getNgayHetHan()) : "",
                dg.isTrangThai() ? "Hoạt động" : "Đã khóa"
            });
        }
    }
    
    private int tinhTuoi(Date ngaySinh) {
        if (ngaySinh == null) return 0;
        return java.time.LocalDate.now().getYear() - 
               (ngaySinh.getYear() + 1900);
    }
    
    private void hienThiChiTietDocGia() {
        int selectedRow = tblDocGia.getSelectedRow();
        if (selectedRow >= 0) {
            DocGiaDTO dg = listDocGia.get(selectedRow);
            txtTenDocGia.setText(dg.getTenDG());
            cboGioiTinh.setSelectedItem(dg.getGioiTinh());
            txtSoDienThoai.setText(dg.getSoDienThoai());
            txtDiaChi.setText(dg.getDiaChi());
            txtMaThe.setText(dg.getMaThe());
            dateNgaySinh.setDate(dg.getNgaySinh());
            dateNgayCap.setDate(dg.getNgayCap());
            dateNgayHetHan.setDate(dg.getNgayHetHan());
        }
    }
    
    private void themDocGia() {
        try {
            DocGiaDTO dg = layThongTinForm();
            if (dg == null) return;
            
            // Tạo mã độc giả mới
            dg.setMaDG("DG" + System.currentTimeMillis());
            dg.setTrangThai(true);
            
            if (docGiaDAO.add(dg)) {
                JOptionPane.showMessageDialog(this, "Thêm độc giả thành công!");
                loadDataToTable();
                xoaForm();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm độc giả thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }
    
    private void capNhatDocGia() {
        try {
            int selectedRow = tblDocGia.getSelectedRow();
            if (selectedRow < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả cần cập nhật!");
                return;
            }
            
            DocGiaDTO dg = layThongTinForm();
            if (dg == null) return;
            
            dg.setMaDG(listDocGia.get(selectedRow).getMaDG());
            dg.setTrangThai(listDocGia.get(selectedRow).isTrangThai());
            
            if (docGiaDAO.update(dg)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadDataToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }
    
    private void xoaDocGia() {
        int selectedRow = tblDocGia.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả cần xóa!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn xóa độc giả này?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION);
                
        if (confirm == JOptionPane.YES_OPTION) {
            String maDG = listDocGia.get(selectedRow).getMaDG();
            if (docGiaDAO.delete(maDG)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                // Cập nhật trạng thái trong listDocGia
                listDocGia.get(selectedRow).setTrangThai(false);
                // Cập nhật hiển thị trong bảng
                DefaultTableModel model = (DefaultTableModel) tblDocGia.getModel();
                model.setValueAt("Đã khóa", selectedRow, 9); // 9 là cột trạng thái
                xoaForm();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }
    
    private void khoiPhucDocGia() {
        int selectedRow = tblDocGia.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả cần khôi phục!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn khôi phục độc giả này?", 
                "Xác nhận khôi phục", 
                JOptionPane.YES_NO_OPTION);
                
        if (confirm == JOptionPane.YES_OPTION) {
            String maDG = listDocGia.get(selectedRow).getMaDG();
            if (docGiaDAO.restore(maDG)) {
                JOptionPane.showMessageDialog(this, "Khôi phục thành công!");
                // Cập nhật trạng thái trong listDocGia
                listDocGia.get(selectedRow).setTrangThai(true);
                // Cập nhật hiển thị trong bảng
                DefaultTableModel model = (DefaultTableModel) tblDocGia.getModel();
                model.setValueAt("Hoạt động", selectedRow, 9); // 9 là cột trạng thái
                xoaForm();
            } else {
                JOptionPane.showMessageDialog(this, "Khôi phục thất bại!");
            }
        }
    }
    
    private void timKiemDocGia() {
        String keyword = txtTimKiem.getText().trim();
        if (!keyword.isEmpty()) {
            listDocGia = docGiaDAO.search(keyword);
            DefaultTableModel model = (DefaultTableModel) tblDocGia.getModel();
            model.setRowCount(0);
            
            for (DocGiaDTO dg : listDocGia) {
                model.addRow(new Object[]{
                    dg.getMaDG(),
                    dg.getTenDG(),
                    dg.getGioiTinh(),
                    dg.getSoDienThoai(),
                    tinhTuoi(dg.getNgaySinh()),
                    dg.getDiaChi(),
                    dg.getMaThe(),
                    dg.getNgayCap() != null ? sdf.format(dg.getNgayCap()) : "",
                    dg.getNgayHetHan() != null ? sdf.format(dg.getNgayHetHan()) : "",
                    dg.isTrangThai() ? "Hoạt động" : "Đã khóa"
                });
            }
        } else {
            loadDataToTable();
        }
    }
    
    private DocGiaDTO layThongTinForm() {
        String tenDG = txtTenDocGia.getText().trim();
        String gioiTinh = (String) cboGioiTinh.getSelectedItem();
        String sdt = txtSoDienThoai.getText().trim();
        String diaChi = txtDiaChi.getText().trim();
        String maThe = txtMaThe.getText().trim();
        Date ngaySinh = dateNgaySinh.getDate();
        Date ngayCap = dateNgayCap.getDate();
        Date ngayHetHan = dateNgayHetHan.getDate();
        
        if (tenDG.isEmpty() || ngaySinh == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc (Tên và Ngày sinh)!");
            return null;
        }
        
        // Nếu có mã thẻ thì phải có ngày cấp và ngày hết hạn
        if (maThe != null && !maThe.trim().isEmpty()) {
            if (ngayCap == null || ngayHetHan == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin thẻ (Ngày cấp và Ngày hết hạn)!");
                return null;
            }
        }
        
        return new DocGiaDTO("", tenDG, gioiTinh, sdt, ngaySinh, diaChi, 
                maThe, ngayCap, ngayHetHan, true);
    }
    
    private void xoaForm() {
        txtTenDocGia.setText("");
        cboGioiTinh.setSelectedIndex(0);
        txtSoDienThoai.setText("");
        txtDiaChi.setText("");
        txtMaThe.setText("");
        dateNgaySinh.setDate(null);
        dateNgayCap.setDate(null);
        dateNgayHetHan.setDate(null);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocgiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame("Quản lý độc giả");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.add(new DocgiaGUI());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JLabel lblTenDocGia;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblMaThe;
    private javax.swing.JLabel lblNgayCap;
    private javax.swing.JLabel lblNgayHetHan;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JTextField txtTenDocGia;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private com.toedter.calendar.JDateChooser dateNgayCap;
    private com.toedter.calendar.JDateChooser dateNgayHetHan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JScrollPane scrTable;
    private javax.swing.JTable tblDocGia;
    // End of variables declaration//GEN-END:variables
}
